# _config.yml

title: qouteall blog
baseurl: "/qouteall-blog" # The name of your repository

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  # REMOVE or ensure 'math_engine: katex' is NOT present.
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-katex